config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: [0,1,2,3,4,5], allow_nil: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= simple_form_for [ @restaurant] do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :phone_number %>
        <%= f.input :category %>
        <%= f.submit "Submit", class: "btn btn-primary" %>
      <% end %>
      
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <h1>Restaurants</h1>
        <%  @restaurants.each do |restaurant| %>
          <p>
            <%= link_to restaurant.name, restaurant_path(restaurant) %>
            <%= link_to "(delete)",
                  restaurant_path(restaurant),
                  method: :delete %>
          </p>
        <% end %>

      <%= link_to "+ add a restaurant", new_restaurant_path %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= simple_form_for [ @restaurant] do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :phone_number %>
        <%= f.input :category %>
        <%= f.submit "Submit", class: "btn btn-primary" %>
      <% end %> 
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <h2><%= "#{@restaurant.name} "%></h2>
      <p><%= "Address: #{@restaurant.address}" %></p>
      <p><%= "Phone: #{@restaurant.phone_number}" %></p>
      <p><%= "Food country: #{@restaurant.category}" %></p>
      <p><%= link_to "Edit the restaurant", edit_restaurant_path %></p>
      <br>
      <br>
      <h5>Reviews</h5>
      <ul class="list-group">
        <% @restaurant.reviews.each do |review| %>
          <li class="list-group-item"><%= "Commentary: #{review.content} #{review.rating} / 5" %>, <%= link_to "Remove", review_path(review), method: :delete, data: { confirm: "Are you sure?" } %></li>
        <% end %>
      </ul>
      <p><%= link_to "+ Add a review",  new_restaurant_review_path(@restaurant)%></p>
      <br>
      <br>
      <p><%= link_to "<- Back", restaurants_path %></p>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <h1>Add Review for <%= @restaurant.name %></h1>
      <%= simple_form_for [ @restaurant, @review ] do |f| %>
      <%= f.input :content %>
      <%= f.input :rating %>
      <%= f.submit "Submit review", class: "btn btn-primary" %>
      <% end %> 
    </div>
  </div>
</div>